spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proscout
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    servlet:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB